-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE feedly_entries (
    id SERIAL PRIMARY KEY,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    published_at timestamp without time zone NOT NULL,
    feedly_id text NOT NULL UNIQUE,
    payload jsonb DEFAULT '{}'::jsonb
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX feedly_entries_pkey ON feedly_entries(id int4_ops);
CREATE UNIQUE INDEX feedly_entries_feedly_id_key ON feedly_entries(feedly_id text_ops);

---

CREATE EXTENSION IF NOT EXISTS tablefunc;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
